#!/usr/bin/env python3

import argparse
import pip.req
import requests


PYPI_URL = 'https://pypi.python.org/pypi/%s/json'


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('path')
    return parser.parse_args()


def main():
    args = parse_args()

    for item in pip.req.parse_requirements(args.path, session='fake'):
        pkg = item.name
        url = PYPI_URL % pkg
        r = requests.get(url)
        r.raise_for_status()
        data = r.json()

        print(pkg)
        for classifier in data['info']['classifiers']:
            print(classifier)
        print()


if __name__ == '__main__':
    main()
